### ISSUE TITLE
TouchBoard2Processing

### ISSUE THREAD

**Issue by v1a1l1e1** [Limulo/linuxday2016#1]
Far comunicare la touchboard via bluetooth con Processing

**Comment by ariutti** [comment]
Il problema non sussiste dal momento che ora la TouchBoard è stata riassegnata alla stazione 7 dove non avrà bisogno di comunicare via BlueTooth.
Ad ogni modo la comunicazione BlueTooth funziona (ottimamente) tra Arduino MEGA e Processing 1.5.1 (che gira sul macbook di Vale).
