### ISSUE TITLE
Stazione 7: alimentazione TouchBoard

### ISSUE THREAD

**Issue by ariutti** [Limulo/linuxday2016#14]
Sapendo che la taouchboard dovrà pilotare 2 servomotori, e che dovrà al contempo essere inclusa all'interno di una scatola, com fare per alimentarla?
Basta una singolo alimentatore (non credo dato che i servomotori da pilotare sono 2)?
E' possibile utilizzare una batteria?

**Comment by ariutti** [comment]
Per separare le alimentazioni (_Touchboard + motori_) è forse il caso di pensare all'uso della **motor shield**?
La motor shield è compatibile con Arduino Leonardo?
- [Motor shield](http://www.arduino.org/products/shields/arduino-motor-shield)
- [più motori su Arduino](http://rcarduino.blogspot.it/2012/04/servo-problems-with-arduino-part-1.html)
- la [guida alla scelta dei motori](https://learn.adafruit.com/adafruit-motor-selection-guide/types-of-motors)di Adafruit

**Comment by v1a1l1e1** [comment]
Abbiamo visto che:
- la touchboard può essere alimentata con il carica-cellulare o con batteria lipo
- la touchboard può pilotare servo motori a patto che questi siano alimentati per conto proprio
- si possono alimentare i servo motori usando un pacco di 4 batterie AA avendo cura di mettere il GND in comune
