### ISSUE TITLE
Bluetooth: 115220 o 9600 baudrate?

### ISSUE THREAD

**Issue by ariutti** [Limulo/linuxday2016#8]
E' possibile fare in modo che i dati ricevuti a **115200 baud** tramite _bluetooth_ vengano poi inoltrati alla porta seriale UART verso il computer a velocità diverse (**9600 baud**)?

L'esempio riportato dalla guida [Sparkfun](https://learn.sparkfun.com/tutorials/using-the-bluesmirf/all) sembra farlo.

Occorre sperimentare e fissare bene le idee.

**Comment by v1a1l1e1** [comment]
L'esempio di Sparkfun risale ad una versione del linguaggio vecchia. I nuovi tutorial sul blue smirf consigliano di usare SEMPRE un baudrate di 115200. E' necessario scendere col baudrate se si utilizza softwareSerial, ma dato che noi usiamo il Mega che dispone di più porte seriali, possiamo tranquillamente usare il baudrate 115200.
